DROP DATABASE IF EXISTS PROCEDURES;

CREATE DATABASE PROCEDURES;

USE PROCEDURES;

CREATE TABLE TB_KEY
(
 ID_KEY      INTEGER PRIMARY KEY AUTO_INCREMENT,
 TX_KEY VARCHAR(19) ,
 ID_USER INTEGER
);

CREATE TABLE TB_USER
(
	ID_USER INTEGER PRIMARY KEY AUTO_INCREMENT,
	NM_USER VARCHAR(50)
);

ALTER TABLE TB_KEY
ADD CONSTRAINT FK_USER_KEY FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER) ;

ALTER TABLE TB_KEY
MODIFY COLUMN ID_USER INTEGER NULL;

ALTER TABLE TB_KEY
ALTER ID_USER SET DEFAULT NULL;

INSERT INTO TB_USER(NM_USER) VALUES('ASTOLFO');
INSERT INTO TB_USER(NM_USER) VALUES('LEAO');
INSERT INTO TB_USER(NM_USER) VALUES('VIRBREITOS');
INSERT INTO TB_USER(NM_USER) VALUES('NOGRIDA');
INSERT INTO TB_USER(NM_USER) VALUES('PRIFATOS');
INSERT INTO TB_USER(NM_USER) VALUES('ASTOLFO');
INSERT INTO TB_USER(NM_USER) VALUES('LEAO');
INSERT INTO TB_USER(NM_USER) VALUES('VIRBREITOS');
INSERT INTO TB_USER(NM_USER) VALUES('NOGRIDA');
INSERT INTO TB_USER(NM_USER) VALUES('PRIFATOS');
INSERT INTO TB_USER(NM_USER) VALUES('NOGRIDA');
INSERT INTO TB_USER(NM_USER) VALUES('PRIFATOS');

INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FRHGFDH',1);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FFJHDH',3);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FFJHDH',2);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FRHGFDH',4);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FFJHDH',5);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FFJHDH',7);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FRHGFDH',6);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FFJHDH',9);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FFJHDH',8);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FRHGFDH',11);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FFJHDH',10);
INSERT INTO TB_KEY(TX_KEY,ID_USER) VALUES('FFJHDH',12);
INSERT INTO TB_KEY(TX_KEY) VALUES('FDHGFDHFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGKHGH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRTRUDJHGFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGVBKH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGKHGH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRTRUDJHGFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGVBKH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGKHGH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRTRUDJHGFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGVBKH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGKHGH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRTRUDJHGFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGVBKH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGKHGH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRTRUDJHGFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGVBKH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGKHGH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRTRUDJHGFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGKHGH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRTRUDJHGFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGVBKH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGKHGH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRTRUDJHGFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGVBKH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGKHGH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRTRUDJHGFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGVBKH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGKHGH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRTRUDJHGFDH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGVBKH');
INSERT INTO TB_KEY(TX_KEY) VALUES('FRGVBKH');
DELIMITER //
CREATE PROCEDURE GET_KEY(IN PAGINA_ATUAL INT, IN MIN_PER_PAGE INT,IN MAX_PER_PAGE INT)
BEGIN
	IF(PAGINA_ATUAL = 1) THEN
		SET MIN_PER_PAGE = MIN_PER_PAGE -1;
    END IF;
	SELECT * FROM TB_KEY
    ORDER BY ID_KEY ASC
	LIMIT MIN_PER_PAGE,MAX_PER_PAGE;
END; //

call GET_KEY(1,1,10);
call GET_KEY(2,10,10);
call GET_KEY(3,20,10);
call GET_KEY(4,30,10);
call GET_KEY(5,40,10);
call GET_KEY(6,50,10);
call GET_KEY(7,60,10);
call GET_KEY(8,70,10);
call GET_KEY(9,80,10);
call GET_KEY(10,90,10);